# Generated by Django 4.2 on 2023-04-20 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_challenge", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
