# Generated by Django 4.2 on 2023-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_challenge", "0002_rename_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
